[package]
name = "chip8-emulator-rust"
version = "0.1.0"
authors = ["sean"]

[dependencies]
rand = "0.3.*"

[dependencies.sdl2]
version = "0.30"
default-features = false
features = ["use_mac_framework", "gfx"]
